spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://37.77.106.193:5432/postgres
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

bot:
  name: dvgKiprBotBot_bot
  token: 5716286799:AAFQJoKTnaDX40h-ZqUdCIUYz4inH_TGz0M

utilValue:
  wifi: D5UTZPMD