version: '2'

services:
  app:
    image: 'dvg-kipr-bot:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bcd_travel_agency_bot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=garbage
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING.JPA.PROPERTIES.HIBERNATE.JDBC.LOB.NON_CONTEXTUAL_CREATION= true
      - SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT= org.hibernate.dialect.PostgreSQLDialect
      - SPRING.JPA.SHOW-SQL=true
      - BOT.NAME=dvg_bcd_agency_travel_bot
      - BOT.TOKEN=6389125314:AAFPFbQuqkNY10K8fz03gcHfW8sbvg627nc
      - BOT.MANAGERID=748689055
      - BOT.MANAGERUSERNAME=prodgaraj

  db:
    container_name: PostgreSQL
    image: "postgres:latest"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=garbage
      - POSTGRES_DB=bcd_travel_agency_bot
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - default

volumes:
  db:
    driver: local